import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/header/header'
import Nav from '@/components/nav/nav'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className=' h-screen'>
      <body className={`${inter.className} dar  h-screen`}>
         <div className="h-screen ">
             {children} 
        </div> 
      </body>
    </html>
  )
}
// 