import './../globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/header/header'
import Nav from '@/components/nav/nav'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function DashboardLayout({ children }) {
  return (
        <div className="flex w-full gap-4 bg-gray_bg dark:bg-white py-3 px-3
         text-black h-fit  ">
           <div className='w-60  '>
             <Nav />
           </div>
           <div className='w-full h-full '>
             <div > 
               <Header />
             </div> 
               {children} 
           </div>
        </div>
  )
}
// 